import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Providers from "src/utils/provider";
import 'react-toastify/dist/ReactToastify.css';
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700", "900"] });
export const metadata: Metadata = {
  title: "Test Frontend",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <Providers>
          <>
            <ToastContainer
              position="top-left"
              autoClose={1000}
              theme="colored"
            />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
